times: 3
time_zone:
  start_point: 0
  end_point: 14
intervals: 30

items:
  - scavenger
  - bridger
  - cpu
  - mem
  - disk

sevices:
  - asr
  - frontend
  - searchall
  - zookeeper
  - resourcemanager
  - lb

scripts:
  cpu: cpu.sh
  mem: mem.sh
  disk: disk.sh
actions:
  - action1:
      host: localhost
      servername: scavenger
      state: stop
      ack: False
      time: now
      recovery_time: 300
      type: sv
log_file: monitoring.log
