times: 2
time_zone:
  start_point: 22
  end_point: 23
recovery_intervals: 30
compent_emiter: False

items:
  - scavenger
  - bridge
  - cpu
  - mem
  - disk

compents:
  - asr
  - frontend
  - searchall
  - zookeeper
  - resourcemanager
  - lb

scripts:
  cpu: cpu.sh
  mem: mem.sh
  disk: disk.sh
  zookeeper: zk.sh
  asr: asr.sh
  frontend: frontend.sh
  searchall: searchall.sh
  resourcemanager: resourcemanager.sh
  lb: lb.sh
actions:
  - action:
      host: localhost
      item: scavenger
      state: stop
      start_time: 30 1 3 * *
      recovery_time: 200
      ack: False
#  - action:
#      host: 192.168.16.122
#      item: cpu
#      state: stop(start|stop|restart)
#      start_time: now(now+time seconds will excute at restart)|* * * * *(cron)|june 8 09:34
#      recovery_time: 200(now+time seconds will excute at restart)|* * * * *(cron)|june 8 09:34
#      ack: False (True|False)
log_file: monitoring.log
intervals: 30
