times: 3
time_zone:
  start_point: 0
  end_point: 15
intervals: 30
recovery_intervals: 30
compent_emiter: False

items:
  - scavenger
  - bridger
  - cpu
  - mem
  - disk

compents:
  - asr
  - frontend
  - searchall
  - zookeeper
  - resourcemanager
  - lb

scripts:
  cpu: cpu.sh
  mem: mem.sh
  disk: disk.sh
  zookeeper: zk.sh
  asr: asr.sh
  frontend: frontend.sh
  searchall: searchall.sh
  resourcemanager: resourcemanager.sh
  lb: lb.sh
actions:
  - action1:
      host: localhost
      servername: scavenger
      state: stop
      ack: False
      time: now
      recovery_time: 200
      type: sv
log_file: monitoring.log
